# Generated by Django 2.1.5 on 2019-01-16 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinePcBuildAssistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Case List',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Interface',
                'verbose_name_plural': 'Interface List',
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specs', models.CharField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlinePcBuildAssistant.Company')),
            ],
            options={
                'verbose_name': 'Motherboard',
                'verbose_name_plural': 'Motherboard List',
            },
        ),
        migrations.CreateModel(
            name='PCIeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'PCIe Type',
                'verbose_name_plural': 'PCIe Types',
            },
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specs', models.CharField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlinePcBuildAssistant.Company')),
            ],
            options={
                'verbose_name': 'Power Supply',
                'verbose_name_plural': 'Power Supply List',
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specs', models.CharField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlinePcBuildAssistant.Company')),
            ],
            options={
                'verbose_name': 'RAM',
                'verbose_name_plural': 'RAM List',
            },
        ),
        migrations.CreateModel(
            name='RamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'RAM Type',
                'verbose_name_plural': 'RAM Types',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlinePcBuildAssistant.Company')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlinePcBuildAssistant.Interface')),
            ],
            options={
                'verbose_name': 'Storage',
                'verbose_name_plural': 'Storage List',
            },
        ),
        migrations.CreateModel(
            name='StorageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Storage Type',
                'verbose_name_plural': 'Storage Types',
            },
        ),
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specs', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlinePcBuildAssistant.Company')),
                ('pcietype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlinePcBuildAssistant.PCIeType')),
            ],
            options={
                'verbose_name': 'GPU',
                'verbose_name_plural': 'GPU List',
            },
        ),
        migrations.AlterModelOptions(
            name='cpu',
            options={'verbose_name': 'CPU', 'verbose_name_plural': 'CPU List'},
        ),
        migrations.AlterModelOptions(
            name='socket',
            options={'verbose_name': 'Socket', 'verbose_name_plural': 'Socket List'},
        ),
        migrations.AddField(
            model_name='storage',
            name='storagetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlinePcBuildAssistant.StorageType'),
        ),
        migrations.AddField(
            model_name='ram',
            name='ramtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlinePcBuildAssistant.RamType'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='pcietype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlinePcBuildAssistant.PCIeType'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='ramtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlinePcBuildAssistant.RamType'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='socket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlinePcBuildAssistant.Socket'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='storageinterface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlinePcBuildAssistant.Interface'),
        ),
        migrations.AddField(
            model_name='case',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlinePcBuildAssistant.Company'),
        ),
    ]
