# Generated by Django 2.1.5 on 2019-01-16 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinePcBuildAssistant', '0003_auto_20190116_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='nameCPU',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='socket',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='motherboard',
            old_name='socket',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='ram',
            old_name='ramtype',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='interface',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='videocard',
            old_name='pcietype',
            new_name='type',
        ),
    ]
