# Generated by Django 2.1.5 on 2019-01-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinePcBuildAssistant', '0005_userbuilds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbuilds',
            options={'verbose_name': 'User Build', 'verbose_name_plural': 'User Builds'},
        ),
    ]
