# Generated by Django 2.1.5 on 2019-01-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinePcBuildAssistant', '0006_auto_20190116_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='powersupply',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ram',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='storage',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userbuilds',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='price',
            field=models.IntegerField(),
        ),
    ]
