# Generated by Django 2.1.5 on 2019-01-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinePcBuildAssistant', '0007_auto_20190116_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='recomendedWatt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocard',
            name='recomendedWatt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
