# Generated by Django 2.1.5 on 2019-01-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinePcBuildAssistant', '0011_auto_20190116_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbuilds',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
