# Generated by Django 2.1.5 on 2019-01-16 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinePcBuildAssistant', '0012_auto_20190116_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='OnlinePcBuildAssistant.Company'),
            preserve_default=False,
        ),
    ]
