# Generated by Django 2.1.5 on 2019-01-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinePcBuildAssistant', '0013_cpu_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbuilds',
            name='link',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
